# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kobe & Barcelona
email: hiroaki.kawai@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Kobe & Barcelona data visualization as an civic hack activity.
baseurl: "/kobe-barcelona" # the subpath of your site, e.g. /blog
url: "http://hkwi.github.io" # the base hostname & protocol for your site
twitter_username: kwi
github_username:  hkwi
google_analytics: UA-1881914-12

# Build settings
markdown: kramdown

gems:
    - jemoji
    - jekyll-mentions
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-feed
